### ISSUE TITLE
Issues with blocks

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/publisher#106]
**1. Category selection is not highlighted in all publisher block option**
![blocks_category](https://user-images.githubusercontent.com/16532279/52893924-b625af80-31dc-11e9-8eda-d93e4642cb4e.jpg)

**2. In spotlight block**
Articles selection not working ..only 1 or none articles showing with this error

Errors
--
Notice: Undefined offset: 7 in file /modules/publisher/blocks/items_spot.php line 50
Notice: Undefined offset: 8 in file /modules/publisher/blocks/items_spot.php line 51
Notice: Undefined property: XoopsModules/Publisher/Item::$posterName in file /modules/publisher/blocks/items_spot.php line 97
Notice: Undefined property: XoopsModules/Publisher/Item::$getDatesub in file /modules/publisher/blocks/items_spot.php line 97
Notice: Undefined variable: itemsCount in file /modules/publisher/blocks/items_spot.php line 98

**3. In spotlight block**
can't save changes made example - Display comment count?

Publisher 1.07 RC1 (02/09/2019) 
XOOPS Version	XOOPS 2.5.10-Beta
PHP Version	7.2.10
mySQL Version	5.7.23

**Comment by mambax7** [comment]
Thanks! I'll look into it this weekend...

**Comment by mambax7** [comment]
This should fix it: https://github.com/XoopsModules25x/publisher/pull/105
