### ISSUE TITLE
Fatal error: Class 'XoopsModules\Publisher\Helper' not found

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/publisher#107]
I noticed when testing xoops 2.5.10  beta and publisher 1.07rci with publisher blocks activated on top page, when i i install and uninstall any module for testing..such as pm and user profile module.....i will receive the fatal; error below on top page.**.refreshing the page and everything backs to normal**

( ! ) Fatal error: Class 'XoopsModules\Publisher\Helper' not found in D:\wamp64\www\10\modules\publisher\include\common.php on line 32

1 | 0.0011 | 321280 | {main}( ) | ...\index.php:0
2 | 0.0018 | 326032 | require_once( 'D:\wamp64\www\10\modules\publisher\header.php' ) | ...\index.php:26
3 | 0.1573 | 4153128 | require_once( 'D:\wamp64\www\10\modules\publisher\include\common.php' ) | ...\header.php:24

----------
Fatal error: Class 'XoopsModules\Publisher\Helper' not found in D:\wamp64\www\10\modules\publisher\include\common.php on line 32
--

1 | 0.0017 | 267928 | {main}( ) | ...\index.php:0
2 | 0.1410 | 4045328 | include( 'D:\wamp64\www\10\header.php' ) | ...\index.php:85
3 | 0.1523 | 4907512 | xos_opal_ThemeFactory->createInstance( ) | ...\header.php:58
4 | 0.1523 | 4911840 | xos_opal_Theme->xoInit( ) | ...\theme.php:81
5 | 0.1677 | 5289120 | xos_logos_PageBuilder->xoInit( ) | ...\theme.php:364
6 | 0.1677 | 5289704 | xos_logos_PageBuilder->retrieveBlocks( ) | ...\theme_blocks.php:49
7 | 0.6242 | 7645784 | xos_logos_PageBuilder->buildBlock( ) | ...\theme_blocks.php:131
8 | 0.6292 | 7647840 | XoopsBlock->buildBlock( ) | ...\theme_blocks.php:197
9 | 0.6369 | 7705728 | include_once( 'D:\wamp64\www\10\modules\publisher\blocks\items_spot.php' ) | ...\xoopsblock.php:213
10 | 0.6380 | 7746680 | require_once( 'D:\wamp64\www\10\modules\publisher\include\common.php' ) | ...\items_spot.php:26

Publisher 1.07 RC1 (02/09/2019)
XOOPS Version | XOOPS 2.5.10-Beta
PHP Version | 5.6.38
mySQL Version | 5.7.23
Wamp Server 3.14

**Comment by mambax7** [comment]
Can you test with PHP 7? This way I can see if this is Publisher, or if it is related to PHP?

**Comment by liomj** [comment]
XOOPS Version | XOOPS 2.5.10-Beta
PHP Version | 7.0.10
mySQL Version | 5.7.14

i got the same error in php7

Error: Error: Class 'XoopsModules/Publisher/Helper' not found in file /modules/publisher/include/common.php line 32

**Comment by mambax7** [comment]
Should be fixed now in 1.07 RC2
