### ISSUE TITLE
TYPO in file /language/english/main.php

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/publisher#109]
TCPDF instead of TCPF line 91 from file publisher/language/english/main.php:

define('_MD_PUBLISHER_ERROR_NO_PDF', '**TCPF** for XOOPS not installed in /class/libraries/vendor/tecnickcom/tcpdf/ <br> Please read the /docs/readme.txt or click on the Help tab to learn how to get it!');

replace with:
define('_MD_PUBLISHER_ERROR_NO_PDF', '**TCPDF** for XOOPS not installed in /class/libraries/vendor/tecnickcom/tcpdf/ <br> Please read the /docs/readme.txt or click on the Help tab to learn how to get it!');

**Comment by mambax7** [comment]
fixed in 1.07 (https://github.com/mambax7/publisher/commit/27367d68ddb81121742c4f6c5cd3a38a66b9c18a)
