### ISSUE TITLE
Error when using Import function

### ISSUE THREAD

**Issue by jemz** [XoopsModules25x/publisher#110]
Trying to import from smartsection module.
Error:
File publisher/admin/import/smartsection.php
Line 75 with "$module->getVar('dirname', 'n')"
Error message: Call to a member function getVar() on null
Temporally working if it is changed to $GLOBALS['xoopsModule']->getVar('dirname', 'n')

Publisher Version | 1.06 Final (also tested with 1.07 RC1)
XOOPS Version | XOOPS 2.5.9
PHP Version | 5.6.30
mySQL Version | 5.6.41-84.1

**Comment by ggoffy** [comment]
should work with current version. could you please test?

**Comment by jemz** [comment]
Sorry to reply so late. It works great now. Also, thanks for fixing categories issue.
