### ISSUE TITLE
Can't delete category

### ISSUE THREAD

**Issue by jemz** [XoopsModules25x/publisher#111]
New Publisher installation, added 1 category and 1 article.
Trying to delete the article, done!
Trying to delete the category, it takes more time waiting, and finally blank page.
Added a sub-category, and tried to delete the sub-category, same issue.

Publisher Version | 1.06 Final
XOOPS Version | XOOPS 2.5.9
PHP Version | 5.6.30
mySQL Version | 5.6.41-84.1

**Comment by ggoffy** [comment]
fixed
