### ISSUE TITLE
Warning just after installation

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/publisher#131]
Warning: constant(): Couldn't find constant PUBLISHER_AUTHOR_LOGOIMG in file /modules/publisher/config/config.php line 88

Name | Version
-- | --
XOOPS | 2.5.11-Beta1
PHP | 7.3.16
mySQL | 8.0.16
Publisher | 1.08 Alpha 1

**Comment by ihackcode** [comment]
PR #133 Should fix this.
