### ISSUE TITLE
Error : TypeError: imagefttext() expects parameter 4 to be int, float given

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/publisher#134]
When try to clone module 
Error : TypeError: imagefttext() expects parameter 4 to be int, float given

Publisher 1.08 Alpha 1 (05/18/2020)

XOOPS Version | XOOPS 2.5.11-Beta1
-- | --
PHP Version | 7.3.12
mySQL Version | 5.7.28

**Comment by ihackcode** [comment]
This should now be fixed with PR #136
