### ISSUE TITLE
Block Image Error

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/publisher#135]
Image is not showing in Block 

examples column block extended
Error : TypeError: imagecreatetruecolor() expects parameter 2 to be int, float given

XOOPS Version | XOOPS 2.5.11-Beta1
-- | --
PHP Version | 7.3.12
mySQL Version | 5.7.28

**Comment by liomj** [comment]
Hi ihackcode the error seems gone from blocks since your last commits, 

i re-download the the latest publisher, now the column extended block is not displaying after activating it

anyone having the same issue ?

**Comment by ihackcode** [comment]
It looks like it is because in_array() is set to also match the datatype.

I might change it to something like below or similar.
https://github.com/ihackcode/publisher/commit/96544c355a1f864997614587deba963e9dfad3d1
