### ISSUE TITLE
archive section - Error : TypeError: mktime() expects parameter 2 to be int, float given

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/publisher#141]
in archive section when i click month to view article, i receive this error

Error : TypeError: mktime() expects parameter 2 to be int, float given

XOOPS Version | XOOPS 2.5.11-Beta1
-- | --
PHP Version | 7.3.12
mySQL Version | 5.7.28

Publisher 1.08 Alpha 2 (07/08/2020)

**Comment by ihackcode** [comment]
This should be fixed in this new PR #144 . Thanks

**Comment by liomj** [comment]
TQ Fixed
