### ISSUE TITLE
archive section - article count problem

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/publisher#142]
XOOPS Version | XOOPS 2.5.11-Beta1
-- | --
PHP Version | 7.3.12
mySQL Version | 5.7.28

Publisher 1.08 Alpha 2 (07/08/2020)

i test this with sample data
i create an article set todays date (july)
no article count for single article in archive page.....i cloned the july article and set the date to June and the article count is display
![1](https://user-images.githubusercontent.com/16532279/87161261-d9cc2700-c2f6-11ea-8871-3587bc9b7b81.jpg)
![2](https://user-images.githubusercontent.com/16532279/87161272-dfc20800-c2f6-11ea-8b47-905d78efae43.jpg)

i cloned the july article and set the date to June and the comment count is display

**Comment by ihackcode** [comment]
Can you see if you are getting this issue with PR #144 . what are your timezone settings set to.?

**Comment by liomj** [comment]
Hi ihackcode, Im at GMT+8. im still having this issue

**Comment by ihackcode** [comment]
I see.. Its an issue when the most recent year has items in only one month.

**Comment by ihackcode** [comment]
Can you see if my fix for archive.php fixes this. https://github.com/ihackcode/publisher/blob/9e965bb8f12b1dfa534fb087336728b2dccafba6/archive.php

**Comment by liomj** [comment]
Im testing with sample data, 

now when i create a new article with today's date, the article count nor the year of and month of the article are not appearing in the archive page

**Comment by mambax7** [comment]
@liomj, can you check if it is now fixed with PR https://github.com/XoopsModules25x/publisher/pull/147

**Comment by liomj** [comment]
thank you fixed
