### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/publisher#149]
Typos

categeory -> category

\language\english\modinfo.php (Line 121)
define('_MI_PUBLISHER_LASTITEMSDSC', 'Select “Yes” to have the list at the bottom of the index and categeory page of the module.');

\docs\lang_diff.txt (Line 34)
changed define('_MI_PUBLISHER_LASTITEMSDSC', 'Select “Yes” to have the list at the bottom of the index and categeory page of the module.');

cateories -> categories

 \language\english\modinfo.php (Line 363)
define('_MI_PUBLISHER_IMGCAT_DSC', 'Please select which cateories from XOOPS Image Manager should be used for adding images to your articles');

errror -> error

\language\english\feedback.php (Line 43)
define('CO_' . $moduleDirNameUpper . '_' . 'FB_SEND_ERROR', 'An errror occured when feedback was sent!');

**Comment by mambax7** [comment]
Thank you! Fixed in: https://github.com/mambax7/publisher/commit/6b27b4aea295c2d0711f8d982ccd6f33e78e4adf
