### ISSUE TITLE
Undefined variable: resultset

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/publisher#150]
When i go to Trello tab (publisher/admin/trello.php)
I get this error:
`Notice: Undefined variable: resultset in file /modules/publisher/class/TrelloDBController.php line 36`

___
My config:

PHP  7.4.9
MYSQL 5.7.31-0ubuntu0.16.04.1
XOOPS 2.5.11-Beta1

**Comment by mambax7** [comment]
Thank you! 
I hope, this fixed it: https://github.com/mambax7/publisher/commit/1a4b3cc70f3ed22d34571aedf2aca46b8f38fb7b
Please reopen, if the errors is still there.
