### ISSUE TITLE
Blank screen at categories tab

### ISSUE THREAD

**Issue by geeronzero** [XoopsModules25x/publisher#151]
Hello.
I've created the first category and after that at categories tab i saw a blank screen. In apache logs i find out there is a leak. I've commented the 212 line (self::displayCategory($thiscat, $level);) at "/modules/publisher/class/Utility.php". Now it works but it's a temporary solution. Also short url not working as i see.

**Comment by mambax7** [comment]
Thank you for letting us know. 
What PHP and Apache are you using? 
What error did you have in the Apache log?

**Comment by geeronzero** [comment]
System overview from CP:
XOOPS Version | XOOPS 2.5.11-Beta1
-- | --
PHP Version | 7.4.12
mySQL Version | 8.0.22
Server API | apache2handler
OS | Linux
fsockopen | On
post_max_size | 8M
max_input_time | 60
output_buffering | 4096
max_execution_time | 30
memory_limit | 128M
file_uploads | On
upload_max_filesize | 2M

Error is: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 50765824 bytes) in Unknown on line 0

i think it's to much for one category without any subcategories.

**Comment by mambax7** [comment]
Thank you so much! I'll look into it. 
Do you have any other modules installed?

**Comment by geeronzero** [comment]
Yes. There are xsitemap and default protector, pm, profile.

**Comment by mambax7** [comment]
Also, did you try to load the sample data first? If yes, is the behavior the same?

**Comment by mambax7** [comment]
This is what I'm having locally here with the test data:
![image](https://user-images.githubusercontent.com/613686/99998527-d066c700-2d8c-11eb-9aa0-11731687231f.png)

**Comment by geeronzero** [comment]
> Also, did you try to load the sample data first? If yes, is the behavior the same?

It's not obviously for me what the sample data is. I've created a category and a subcategory but the behavior is the same.

**Comment by mambax7** [comment]
Do you see this on your Home tab?
If yes, please click on it and import the sample data, and then check the Category Tab:

![image](https://user-images.githubusercontent.com/613686/99999733-95659300-2d8e-11eb-848a-bb2ebec3a9a0.png)

**Comment by geeronzero** [comment]
Yep, now it works. Why so?

**Comment by mambax7** [comment]
That's what we need to find out. 
Please describe exactly the steps how you created your category and subcategory, and how did you set the permissions there, so so I could try to recreate it here.

**Comment by mambax7** [comment]
You can also delete the Sample data, and do create again your Category and Subcategory. If it doesn't work, then 
a) click on the button "Export Tables to YAML", 
b) go to \modules\publisher\testdata\english\ (if you use it in English, or your local language)
c) zip the content of that folder, and post it here

**Comment by geeronzero** [comment]
The error appears when i change moderator in category properties.
