### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/publisher#156]
On the administration side, the link to the "approve" icon goes there:

yourwebsite/modules/publisher/assets/images/**_icons_**/16/approve.gif

while it is here:

yourwebsite/modules/publisher/assets/images/**_icon_**/16/approve.gif

![image](https://user-images.githubusercontent.com/4613970/103740002-c2949a80-4ff6-11eb-8d8c-69229c964efb.png)

**Comment by mambax7** [comment]
Thanks!  fixed in https://github.com/XoopsModules25x/publisher/pull/159
