### ISSUE TITLE
Issue with files attachment

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/publisher#161]
1. try edit any article with attachment then edit the title or description of the attachment. After submitting, the status of the attachment is changed to inactive (0)

2. no edit button to change back the status of the file attachment to active, need to change it manually in db 

https://www.pictr.com/images/2021/03/04/7XLJ2O.jpg

XOOPS Version | XOOPS 2.5.11-Beta1
-- | --
PHP Version | 7.3.12
mySQL Version | 5.7.28
Publisher|  1.08 Alpha 4 (01/12/2021)

**Comment by mambax7** [comment]
Thanks, I'll look into it this weekend

**Comment by mambax7** [comment]
fixed in https://github.com/mambax7/publisher/commit/b66f2721cd1e3b0b5eed925c4c44c3cd030a88f9
