### ISSUE TITLE
archive problem 

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/publisher#162]
1. install publisher
2. import  sample data
3. Go to archive page
4. select any month
5. error below is display

Error : TypeError: mktime() expects parameter 2 to be int, float given

XOOPS Version | XOOPS 2.5.11-Beta1
-- | --
PHP Version | 7.3.12
mySQL Version | 5.7.28
Publisher Version |  1.08 Alpha 4 (01/12/2021)

**Comment by mambax7** [comment]
Thanks, I'll look into it this weekend

**Comment by mambax7** [comment]
OK, it's fixed in the upcoming next release

**Comment by mambax7** [comment]
Fixed in https://github.com/mambax7/publisher/commit/b66f2721cd1e3b0b5eed925c4c44c3cd030a88f9
