### ISSUE TITLE
Can't upload file

### ISSUE THREAD

**Issue by boscorelly** [XoopsModules25x/publisher#19]
Hi,

i can't add more files to articles.

It says it's added but nothing is done : no file uploaded, nothing in database.

To know, i have a simlink for upload folder because i have 1 xoops for extranet and another xoops on intranet (same database).
Worked perfectly until i upgrade to 2.5.7.2 and publisher 1.02 final (previously 2.5.7 and 1.02 beta 3).

**Comment by mambax7** [comment]
We need more information - how can I reproduce it? 
For example, what folders are you using? What are the error messages? Can you check error logs (e.g. PHP error log, and MySQL error log)?
Please try to be in my shoes: just coming and saying that you can't upload is not helpful, if I can't reproduce it :(

**Comment by boscorelly** [comment]
Le 19/01/2016 09:59, Mamba (Michael Beck) a écrit :
> We need more information - how can I reproduce it?
> For example, what folders are you using? What are the error messages?
> Can you check error logs (e.g. PHP error log, and MySQL error log)?
> Please try to be in my shoes: just coming and saying that you can't
> upload is not helpful, if I can't reproduce it :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XoopsModules25x/publisher/issues/19#issuecomment-172780239>.
>

Hi,

i just upgraded xoops from xoops 2.5.7 to 2.5.7.1 and 2.5.7.2 and then 
upgraded publisher from 1.02 beta 3 to 1.02 final.

the public site is in /home/web/domain.tld/www/
the intranet site is in /home/web/domain.tld/www.intra/

both sites have the same files (i upgrade same time everytime i upgrade).

the /home/web/domain.tld/www.intra/uploads/ is a symlink to 
/home/web/domain.tld/www/uploads/

it's like this since 3 years at least. It worked fine since i upgraded 
to the latests versions.

There is no error message, the only displayed message is "things added 
user side".

i'll check to enable php log file :)

**Comment by boscorelly** [comment]
i can't have any php output with php-fpm and nginx... :(

**Comment by mambax7** [comment]
What is php-fpm? 
Unfortunately, I have no experience with nginx :(

**Comment by boscorelly** [comment]
Hi,

http://php-fpm.org/

PHP-FPM (FastCGI Process Manager) is an alternative PHP FastCGI

**Comment by chaoos2** [comment]
I confirm, I also can not upload files. And the same goes for pictures - It also can not upload.
PHP 7.1.1, MariaDB 10.1.21, Xoops 2.5.9 Beta1.

**Comment by bleekk** [comment]
have you first created a category in the image manager?

**Comment by chaoos2** [comment]
bleekk you're right, I did not include any category in the Image Manager. After creating a category that works properly. Thanks
_It would be good to ensure this issue some warnings._
