### ISSUE TITLE
Bug in class/item.php

### ISSUE THREAD

**Issue by myxoops** [XoopsModules25x/publisher#20]
Hi,

I found a bug in class/item.php

Line 730
`$summary = $this->summary($max_char_summary);
                if (!$summary) {
                    $summary = $this->body($max_char_summary);
                }`

should be
`$summary = $this->getSummary($max_char_summary);
                if (!$summary) {
                    $summary = $this->getBody($max_char_summary);
                }`

you need to use the new methods getSummary and getBody

**Comment by mambax7** [comment]
Thank you. Fixed in: https://github.com/mambax7/publisher/commit/ca3f3fb70a6f419851367053c850275be2500bd7
