### ISSUE TITLE
Recent Articles (detail) block doesn't show

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/publisher#29]
Module downloaded here:
https://github.com/XoopsModules25x/publisher/releases/tag/1.03_RC1

It seems that Recent Articles (detail) block doesn't show.

![image](https://cloud.githubusercontent.com/assets/4613970/16699396/25ac3ef0-4554-11e6-8fc2-78f1c3b35e72.png)

![image](https://cloud.githubusercontent.com/assets/4613970/16699423/5253b3ca-4554-11e6-97d4-c70efd923589.png)

___

My config:

PHP: 5.6.11-1ubuntu3.4
MYSQL: 5.6.30
XOOPS: 2.5.8 english version
ModuleAdmin: 1.2

**Comment by mambax7** [comment]
Fixed in https://github.com/XoopsModules25x/publisher/commit/7fadb8bd5a502604d9979794c9b5dd02291eda07
