### ISSUE TITLE
PDF generation for articles is not working

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/publisher#30]
Module downloaded here:
https://github.com/XoopsModules25x/publisher/releases/tag/1.03_RC1

PDF generation for articles is not working.

error:
The requested URL /modules/publisher/viewtopic.php was not found on this server.

___

My config:

PHP: 5.6.11-1ubuntu3.4
MYSQL: 5.6.30
XOOPS: 2.5.8 english version
ModuleAdmin: 1.2

**Comment by mambax7** [comment]
You can download [TCPDF from GitHub](https://github.com/tecnickcom/TCPDF/releases), and then copy the content of the zip file into:
```
/class/libraries/vendor/tecnickcom/tcpdf/
```
and your PDF should work without any problems.
