### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/publisher#31]
Module downloaded here:
https://github.com/XoopsModules25x/publisher/releases/tag/1.03_RC1

When I go to:
/modules/profile/userinfo.php?uid=2

I get this error:
Warning: Invalid argument supplied for foreach() in file /modules/publisher/include/search.inc.php line 50

But I don't get this error when I go to:
 /modules/profile/userinfo.php?uid=1

___

My config:

PHP: 5.6.11-1ubuntu3.4
MYSQL: 5.6.30
XOOPS: 2.5.7.2 english version
ModuleAdmin: 1.2

**Comment by mambax7** [comment]
Fixed in: https://github.com/XoopsModules25x/publisher/commit/7fadb8bd5a502604d9979794c9b5dd02291eda07
