### ISSUE TITLE
Unknown: preg_replace()

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/publisher#33]
When I print an article, I get this error (modules/publisher/print.php?itemid=1):

Unknown: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in file /modules/publisher/include/functions.php line 147
___

My config:

PHP: 5.6.11-1ubuntu3.4
MYSQL: 5.6.30
XOOPS: 2.5.8 english version
ModuleAdmin: 1.2

**Comment by mambax7** [comment]
Fixed in https://github.com/XoopsModules25x/publisher/commit/18d616d1e6353fc75ee2e7363d8fcb31b9ba615a
