### ISSUE TITLE
date format example: wrong url into preferences

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/publisher#35]
publisher/language/english/modinfo/php line 47:
"Select a display style. Example: 'd-M-Y H:i' translates to '30-Mar-2004 22:35'<br><a href=\'http://jp.php.net/date\'>Refer to the PHP manual for more display options.</a>");

Wrong url. The link take back the url of the site:

![image](https://cloud.githubusercontent.com/assets/4613970/16723702/e15fe57e-474e-11e6-8718-065b07bd7614.png)

The URL has changed too.

Before:
http://jp.php.net/date

Now:
http://jp2.php.net/manual/fr/function.date.php

Publisher module downloaded from here:
https://github.com/mambax7/publisher

**Comment by mambax7** [comment]
fixed in https://github.com/mambax7/publisher/commit/2dff611e444b77c342e5fad11306b11482783e43

Thank you!
