### ISSUE TITLE
search access

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/publisher#36]
I have all the rights, but I don't have access to the Publisher module search:
modules/publisher/search.php

I get this message:
Sorry, you don't have the permission to access this area.

![image](https://cloud.githubusercontent.com/assets/4613970/16724411/d6a89028-4752-11e6-9b29-ca4e07468108.png)

**Comment by mambax7** [comment]
You need to set the Search permissions in "Permissions"

**Comment by cesagonchu** [comment]
Yes I did
