### ISSUE TITLE
wrong date article creation on admin side

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/publisher#41]
All articles created on admin side have the same and wrong date 31-Dec-1969 :

![image](https://cloud.githubusercontent.com/assets/4613970/16742935/5158b562-47aa-11e6-9e79-9bcffe4a977d.png)

**Comment by mambax7** [comment]
What date format do you have in the Preferences?  Did you change anything there?

**Comment by mambax7** [comment]
OK, I found what it was. 
When you don't set the Permissions to allow the Author to modify the "Published  Date", the date is saved wrongly. 
When you set the Permissions to yes, then the date is visible and is saved correctly.  
Thanks for reporting, it will be fixed soon....

**Comment by mambax7** [comment]
Fixed in https://github.com/XoopsModules25x/publisher/pull/42/commits/d81c7d9d0dd11a9cee1ef15a6168ec938d8d2a78
