### ISSUE TITLE
Add a line in the Article tab

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/publisher#43]
Since we still have this error when trying to convert an article into PDF:

![image](https://cloud.githubusercontent.com/assets/4613970/16758844/5d7df6b2-4814-11e6-8551-a7c8aa731e5d.png)

and if the webmaster doesn't read the help page, I think we should add a line  (with color) in the Article tab, to specify the wemaster he has to install TCPDF.
We should also provide a link to help page into this line:

![image](https://cloud.githubusercontent.com/assets/4613970/16758990/0d4e6da6-4815-11e6-90bc-5da28426de26.png)

Or maybe someone has a better idea?

**Comment by mambax7** [comment]
We definitely have to remove the link to viewtopic.php. The makepdf.php file came from NewBB module, and the link was not removed, so this needs to be fixed. 
In the Preferences, there is an option to show the PDF icon. I'll set it in new installation as "No", and add info there that they need the TCPDF file, and they should read the "readme.txt" file for info how to get it.

**Comment by cesagonchu** [comment]
Ok :-)

**Comment by mambax7** [comment]
Please check out the solution: https://github.com/mambax7/publisher/commit/3612ad256c8fb287d329e4575e0814e1a243b594
