### ISSUE TITLE
PDF Generation Improvement

### ISSUE THREAD

**Issue by geekwright** [XoopsModules25x/publisher#49]
Publisher generated PDF are not respecting xoopscode formatting. Code changes have been suggested in makepdf.php, at line 56 replace this:
```php
$content .= $itemObj->plainMaintext();
```
with this:
```php
$content .= $itemObj->getBody();
$content = str_replace('[pagebreak]','',$content);
```
See xoops.org forums: 
http://xoops.org/modules/newbb/viewtopic.php?post_id=360860#forumpost360860

**Comment by mambax7** [comment]
https://github.com/XoopsModules25x/publisher/releases/tag/1.04_RC1b
