### ISSUE TITLE
ERROR: Could not insert template

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/publisher#5]
When I install Publisher module, I get these 2 errors:
ERROR: Could not insert template publisher_footer.tpl to the database.
ERROR: Could not insert template publisher_submit.tpl to the database.

![image](https://cloud.githubusercontent.com/assets/4613970/9951542/fa1fa6b0-5dc7-11e5-96c5-c49531ba8d12.png)

PHP: 5.6.4-4ubuntu6.2
MYSQL: 5.6.25-0ubuntu0.15.04.1
XOOPS: 2.5.7.1 (english)
ModuleAdmin: 1.2

Publisher downloaded from here:
http://github.com/mambax7/publisher

**Comment by mambax7** [comment]
https://github.com/mambax7/publisher/commit/898004814f38791e71a844801330ee3ff2ed6a66
