### ISSUE TITLE
xoopsfilterinput.php

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/publisher#6]
When I want to create a category (/modules/publisher/admin/category.php) and select another editor, I get this error:
Notice: Array to string conversion in file /class/xoopsfilterinput.php line 217

___

My config:

PHP version: 5.6.4-4ubuntu6.2
MYSQL version: 5.6.25-0ubuntu0.15.04.1
XOOPS version: 2.5.7.1

**Comment by mambax7** [comment]
Fixed: https://github.com/mambax7/publisher/commit/a96eced770199b5f2acc18fc2d8968d5ba2720ae
