### ISSUE TITLE
Not working with tag Module

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/publisher#60]
when we use tag module the submit page is not working

xoopsFormtag is deprecated use tagFormtag

disabling the tag in Permission the module works fine

https://github.com/xoopsmodules25x/tag/

**Comment by bleekk** [comment]
I have tested it now with xoops 2.5.9 
the tag module from your link
and publisher from here https://github.com/bleekk/publisher (here are only 2 bugs fixed, not related to tags)

can you please describe your problem little bit better. thanks

**Comment by liomj** [comment]
it seems this has been fixed..in the last commit
