### ISSUE TITLE
items by same author not working

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/publisher#62]
Fatal error: Class 'XoopsLocal' not found in D:\wamp\www\test\modules\publisher\author_items.php on line 63

XOOPS Version	XOOPS 2.5.9-Beta2
PHP Version	5.6.25
mySQL Version	5.7.14
Publisher 1.05 Beta 1 (02/19/2017)

**Comment by bleekk** [comment]
fixed here https://github.com/bleekk/publisher
