### ISSUE TITLE
7 errors on install

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/publisher#65]
I get 7 errors on install with latest version of Publisher (1.05 Beta 1) and Xoops 2.5.9 beta 3:

Notice: Constant PUBLISHER_UPLOAD_PATH already defined in file /modules/publisher/include/config.php line 42

Notice: Undefined variable: uploadFolders in file /modules/publisher/include/oninstall.php line 71

Warning: array_keys() expects parameter 1 to be array, null given in file /modules/publisher/include/oninstall.php line 71

Warning: Invalid argument supplied for foreach() in file /modules/publisher/include/oninstall.php line 71

Notice: Undefined variable: blankFiles in file /modules/publisher/include/oninstall.php line 76

Warning: array_keys() expects parameter 1 to be array, null given in file /modules/publisher/include/oninstall.php line 76

Warning: Invalid argument supplied for foreach() in file /modules/publisher/include/oninstall.php line 76

___
My config:
XOOPS Version	XOOPS 2.5.9-Beta3
PHP Version	7.0.15-0ubuntu0.16.10.4
mySQL Version	5.7.17-0ubuntu0.16.10.1
Server API	apache2handler
OS	Linux

**Comment by bleekk** [comment]
Fixed here https://github.com/bleekk/publisher

**Comment by cesagonchu** [comment]
tyvm bleekk! ;-)
