### ISSUE TITLE
no page styling when editing any category

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/publisher#87]
no page styling when editing category

Publisher 1.06 Beta 2 (12/09/2017) 
XOOPS Version | XOOPS 2.5.9
PHP Version | 5.6.32
mySQL Version | 5.6.38

**Comment by mambax7** [comment]
See if the latest changes in my fork fixed that: https://github.com/mambax7/publisher
If they did, I'll commit here...

**Comment by liomj** [comment]
solved
