### ISSUE TITLE
Rating fails using the URL rewrite method "path info"

### ISSUE THREAD

**Issue by zyspec** [XoopsModules25x/publisher#88]
> Using the URL rewrite method "path info", the Rating vote fails: if you click on a star the vote has no effect.

Information taken from https://xoops.org/modules/newbb/viewtopic.php?topic_id=78391

**Comment by myblackrx** [comment]
it is also not working in htaccess mode

**Comment by liomj** [comment]
hope anyone can help fix this error...

im using htaccess but cant use the rating feature :-(

**Comment by ihackcode** [comment]
See if the .htaccess file in this pull request fixes your issue. #127

**Comment by ihackcode** [comment]
#128
