### ISSUE TITLE
Separate print and pdf button from <{$item.adminlink}>

### ISSUE THREAD

**Issue by myblackrx** [XoopsModules25x/publisher#89]
Hi i have suggestion for publisher module

can the pdf and print button page be separated from the  <{$item.adminlink}> in the template

so we have the flexibility to beautify the template something like putting the print and pdf button near the title

right now it is tie with edit, delete, duplicate link

**Comment by liomj** [comment]
This is implemented in my commit https://github.com/XoopsModules25x/publisher/pull/125/commits
