### ISSUE TITLE
Fatal error: Class 'Xoopsmodules\publisher\PublisherSession' not found 

### ISSUE THREAD

**Issue by myblackrx** [XoopsModules25x/publisher#90]
when trying to upload file in submit page

Fatal error: Class 'Xoopsmodules\publisher\PublisherSession' not found in E:\wamp64\www\xoops\modules\publisher\class\Utility.php on line 1078

XOOPS Version | XOOPS 2.5.9
PHP Version | 5.6.25
mySQL Version | 5.7.14
Publisher 1.06 Beta 2 (12/09/2017)

**Comment by liomj** [comment]
its working fine in Publisher 1.07 RC1 (02/09/2019) 
XOOPS Version | XOOPS 2.5.10-Beta
PHP Version | 5.6.38
mySQL Version | 5.7.23
