### ISSUE TITLE
Futur Post appeared in blocks

### ISSUE THREAD

**Issue by myblackrx** [XoopsModules25x/publisher#91]
If we set the date article to be in the future date.. the article appaear in publisher blocks for guest and admin

in publisher main page or category page it is ok, we dont see the future post until the date

XOOPS 2.59 Final
Publisher Final 1.05

**Comment by liomj** [comment]
i tried to change my article to a later date and it does not appear in my blocks
but i can't see the articles in my article list when the date of the articles is in future....

i thinks that is a problem


Publisher 1.07 RC1 (02/09/2019)
XOOPS Version | XOOPS 2.5.10-Beta
PHP Version | 5.6.38
mySQL Version | 5.7.23

**Comment by mambax7** [comment]
You mean, you don't see it as the admin?

**Comment by liomj** [comment]
yes as admin of the site ...i dont see the future post  in publisher admin article list

**Comment by mambax7** [comment]
Should be fixed in https://github.com/XoopsModules25x/publisher/releases/tag/1.07_RC2
Please test
